workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      codemagic: default
    environment:
      flutter: stable
      xcode: latest
      node: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM