name: payment_app
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  google_mlkit_barcode_scanning: ^0.13.0
  image_picker: ^1.1.2
  qr_code_scanner_plus: ^2.0.9+1
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.2.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  app_settings: ^5.2.0
  flutter_dotenv: ^5.2.1
  showcaseview: ^4.0.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/konoha.png
    - assets/images/google.png
    - assets/icons/icon.png
    - assets/images/starting_wallpaper.png

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
